export const metricsGraphJson = {
  annotations: {
    list: [
      {
        $$hashKey: 'object:3299',
        builtIn: 1,
        datasource: 'prometheus',
        enable: true,
        hide: true,
        iconColor: 'rgba(0, 211, 255, 1)',
        limit: 100,
        name: 'Annotations & Alerts',
        showIn: 0,
        type: 'dashboard',
      },
    ],
  },
  editable: true,
  gnetId: null,
  graphTooltip: 0,
  links: [],
  panels: [
    {
      cacheTimeout: null,
      colorBackground: false,
      colorValue: true,
      colors: [
        'rgba(245, 54, 54, 0.9)',
        'rgba(237, 129, 40, 0.89)',
        'rgba(50, 172, 45, 0.97)',
      ],
      datasource: 'prometheus',
      decimals: null,
      editable: true,
      error: false,
      format: 'none',
      gauge: {
        maxValue: 100,
        minValue: 0,
        show: false,
        thresholdLabels: false,
        thresholdMarkers: true,
      },
      gridPos: {
        h: 5,
        w: 12,
        x: 0,
        y: 0,
      },
      id: 1,
      interval: null,
      links: [],
      mappingType: 1,
      mappingTypes: [
        {
          name: 'value to text',
          value: 1,
        },
        {
          name: 'range to text',
          value: 2,
        },
      ],
      maxDataPoints: 100,
      nullPointMode: 'connected',
      nullText: null,
      postfix: ' messages',
      postfixFontSize: '50%',
      prefix: '',
      prefixFontSize: '30%',
      rangeMaps: [
        {
          from: 'null',
          text: 'N/A',
          to: 'null',
        },
      ],
      sparkline: {
        fillColor: 'rgba(31, 118, 189, 0.18)',
        full: false,
        lineColor: 'rgb(31, 120, 193)',
        show: false,
      },
      tableColumn: '',
      targets: [
        {
          datasource: 'prometheus',
          expr: 'sum(kafka_log_log_value{ name="LogEndOffset" , topic = "transactions" }) - sum(kafka_log_log_value{ name="LogStartOffset", topic = "transactions" })',
          intervalFactor: 2,
          legendFormat: '',
          metric: '',
          refId: 'A',
          step: 20,
        },
      ],
      thresholds: '',
      title: 'transactions topic',
      transparent: false,
      type: 'singlestat',
      valueFontSize: '200%',
      valueMaps: [
        {
          op: '=',
          text: 'N/A',
          value: 'null',
        },
      ],
      valueName: 'current',
    },
    {
      cacheTimeout: null,
      colorBackground: false,
      colorValue: true,
      colors: ['#7eb26d', 'rgba(237, 129, 40, 0.89)', '#d44a3a'],
      datasource: '-- Grafana --',
      format: 'h',
      gauge: {
        maxValue: 100,
        minValue: 0,
        show: false,
        thresholdLabels: false,
        thresholdMarkers: true,
      },
      gridPos: {
        h: 5,
        w: 12,
        x: 12,
        y: 0,
      },
      id: 15,
      interval: null,
      links: [],
      mappingType: 1,
      mappingTypes: [
        {
          name: 'value to text',
          value: 1,
        },
        {
          name: 'range to text',
          value: 2,
        },
      ],
      maxDataPoints: 100,
      nullPointMode: 'connected',
      nullText: null,
      postfix: '',
      postfixFontSize: '50%',
      prefix: '',
      prefixFontSize: '50%',
      rangeMaps: [
        {
          from: 'null',
          text: 'N/A',
          to: 'null',
        },
      ],
      sparkline: {
        fillColor: 'rgba(31, 118, 189, 0.18)',
        full: false,
        lineColor: 'rgb(31, 120, 193)',
        show: false,
      },
      tableColumn: '',
      targets: [
        {
          $$hashKey: 'object:2973',
          expr: 'java_lang_runtime_uptime',
          format: 'time_series',
          hide: false,
          intervalFactor: 2,
          refId: 'A',
        },
      ],
      thresholds: '',
      title: 'Kafka Broker Uptime',
      type: 'singlestat',
      valueFontSize: '80%',
      valueMaps: [
        {
          op: '=',
          text: 'N/A',
          value: 'null',
        },
      ],
      valueName: 'avg',
    },
    {
      aliasColors: {},
      bars: false,
      dashLength: 10,
      dashes: false,
      datasource: 'prometheus',
      editable: true,
      error: false,
      fill: 1,
      grid: {},
      gridPos: {
        h: 8,
        w: 12,
        x: 0,
        y: 5,
      },
      id: 2,
      legend: {
        alignAsTable: false,
        avg: false,
        current: true,
        hideEmpty: false,
        hideZero: false,
        max: false,
        min: false,
        rightSide: false,
        show: true,
        total: false,
        values: true,
      },
      lines: true,
      linewidth: 2,
      links: [],
      nullPointMode: 'connected',
      percentage: false,
      pointradius: 5,
      points: false,
      renderer: 'flot',
      seriesOverrides: [],
      spaceLength: 10,
      stack: false,
      steppedLine: false,
      targets: [
        {
          expr: 'kafka_server_brokertopicmetrics_oneminuterate{name="BytesInPerSec"}',
          intervalFactor: 2,
          refId: 'A',
          step: 2,
        },
        {
          expr: 'kafka_server_brokertopicmetrics_oneminuterate{name="BytesOutPerSec"}',
          intervalFactor: 2,
          legendFormat: '',
          refId: 'B',
          step: 2,
        },
      ],
      thresholds: [],
      timeFrom: null,
      timeShift: null,
      title: 'Topic BytesIn to BytesOut Rate',
      tooltip: {
        msResolution: false,
        shared: true,
        sort: 0,
        value_type: 'cumulative',
      },
      transparent: false,
      type: 'graph',
      xaxis: {
        buckets: null,
        mode: 'time',
        name: null,
        show: true,
        values: [],
      },
      yaxes: [
        {
          format: 'Bps',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
        {
          format: 'short',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
      ],
    },
    {
      aliasColors: {},
      bars: false,
      dashLength: 10,
      dashes: false,
      datasource: 'prometheus',
      editable: true,
      error: false,
      fill: 1,
      grid: {},
      gridPos: {
        h: 8,
        w: 12,
        x: 12,
        y: 5,
      },
      id: 6,
      legend: {
        avg: false,
        current: false,
        max: false,
        min: false,
        show: true,
        total: false,
        values: false,
      },
      lines: true,
      linewidth: 2,
      links: [],
      nullPointMode: 'connected',
      percentage: false,
      pointradius: 5,
      points: false,
      renderer: 'flot',
      seriesOverrides: [],
      spaceLength: 10,
      stack: false,
      steppedLine: false,
      targets: [
        {
          expr: 'kafka_network_processor_value',
          intervalFactor: 2,
          refId: 'A',
          step: 2,
        },
      ],
      thresholds: [],
      timeFrom: null,
      timeShift: null,
      title: 'Network Processor Idle (%)',
      tooltip: {
        msResolution: false,
        shared: true,
        sort: 0,
        value_type: 'cumulative',
      },
      type: 'graph',
      xaxis: {
        buckets: null,
        mode: 'time',
        name: null,
        show: true,
        values: [],
      },
      yaxes: [
        {
          format: 'percentunit',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
        {
          format: 'short',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
      ],
    },
    {
      aliasColors: {},
      bars: false,
      dashLength: 10,
      dashes: false,
      datasource: 'prometheus',
      editable: true,
      error: false,
      fill: 1,
      grid: {},
      gridPos: {
        h: 7,
        w: 12,
        x: 0,
        y: 13,
      },
      id: 4,
      legend: {
        avg: false,
        current: false,
        max: false,
        min: false,
        show: true,
        total: false,
        values: false,
      },
      lines: true,
      linewidth: 2,
      links: [],
      nullPointMode: 'connected',
      percentage: false,
      pointradius: 5,
      points: false,
      renderer: 'flot',
      seriesOverrides: [],
      spaceLength: 10,
      stack: false,
      steppedLine: false,
      targets: [
        {
          expr: 'java_lang_memory_heapmemoryusage_used',
          intervalFactor: 2,
          legendFormat: '',
          refId: 'A',
          step: 2,
        },
      ],
      thresholds: [],
      timeFrom: null,
      timeShift: null,
      title: 'JVM Heap Memory Usage',
      tooltip: {
        msResolution: false,
        shared: true,
        sort: 0,
        value_type: 'cumulative',
      },
      type: 'graph',
      xaxis: {
        buckets: null,
        mode: 'time',
        name: null,
        show: true,
        values: [],
      },
      yaxes: [
        {
          format: 'bytes',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
        {
          format: 'short',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
      ],
    },
    {
      aliasColors: {},
      bars: false,
      dashLength: 10,
      dashes: false,
      datasource: 'prometheus',
      editable: true,
      error: false,
      fill: 1,
      grid: {},
      gridPos: {
        h: 7,
        w: 12,
        x: 12,
        y: 13,
      },
      id: 7,
      legend: {
        avg: false,
        current: false,
        max: false,
        min: false,
        show: true,
        total: false,
        values: false,
      },
      lines: true,
      linewidth: 2,
      links: [],
      nullPointMode: 'connected',
      percentage: false,
      pointradius: 5,
      points: false,
      renderer: 'flot',
      seriesOverrides: [],
      spaceLength: 10,
      stack: false,
      steppedLine: false,
      targets: [
        {
          expr: 'java_lang_operatingsystem_systemcpuload',
          intervalFactor: 2,
          refId: 'A',
          step: 2,
        },
      ],
      thresholds: [],
      timeFrom: null,
      timeShift: null,
      title: 'JVM System CPU Load',
      tooltip: {
        msResolution: false,
        shared: true,
        sort: 0,
        value_type: 'cumulative',
      },
      type: 'graph',
      xaxis: {
        buckets: null,
        mode: 'time',
        name: null,
        show: true,
        values: [],
      },
      yaxes: [
        {
          format: 'percentunit',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
        {
          format: 'short',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
      ],
    },
    {
      aliasColors: {},
      bars: false,
      dashLength: 10,
      dashes: false,
      datasource: 'prometheus',
      editable: true,
      error: false,
      fill: 1,
      grid: {},
      gridPos: {
        h: 7,
        w: 12,
        x: 0,
        y: 20,
      },
      id: 13,
      legend: {
        alignAsTable: false,
        avg: false,
        current: false,
        max: false,
        min: false,
        show: true,
        total: false,
        values: false,
      },
      lines: true,
      linewidth: 2,
      links: [],
      nullPointMode: 'connected',
      percentage: false,
      pointradius: 5,
      points: false,
      renderer: 'flot',
      seriesOverrides: [],
      spaceLength: 10,
      stack: false,
      steppedLine: false,
      targets: [
        {
          expr: 'kafka_server_kafkarequesthandlerpool_oneminuterate',
          intervalFactor: 2,
          legendFormat: '',
          metric: 'kafka_server_replicafetchermanager_value',
          refId: 'A',
          step: 2,
        },
      ],
      thresholds: [],
      timeFrom: null,
      timeShift: null,
      title: 'Request Handler Idle (%)',
      tooltip: {
        msResolution: false,
        shared: true,
        sort: 0,
        value_type: 'cumulative',
      },
      type: 'graph',
      xaxis: {
        buckets: null,
        mode: 'time',
        name: null,
        show: true,
        values: [],
      },
      yaxes: [
        {
          format: 'percentunit',
          label: '',
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
        {
          format: 'short',
          label: '',
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
      ],
    },
    {
      aliasColors: {},
      bars: false,
      dashLength: 10,
      dashes: false,
      datasource: 'prometheus',
      editable: true,
      error: false,
      fill: 1,
      grid: {},
      gridPos: {
        h: 7,
        w: 12,
        x: 12,
        y: 20,
      },
      id: 11,
      legend: {
        avg: false,
        current: false,
        max: false,
        min: false,
        show: false,
        total: false,
        values: false,
      },
      lines: true,
      linewidth: 2,
      links: [],
      nullPointMode: 'connected',
      percentage: false,
      pointradius: 5,
      points: false,
      renderer: 'flot',
      seriesOverrides: [],
      spaceLength: 10,
      stack: false,
      steppedLine: false,
      targets: [
        {
          expr: 'kafka_network_requestmetrics_oneminuterate',
          intervalFactor: 2,
          legendFormat: '',
          refId: 'A',
          step: 2,
        },
      ],
      thresholds: [],
      timeFrom: null,
      timeShift: null,
      title: 'Kafka Network Request Metrics',
      tooltip: {
        msResolution: true,
        shared: true,
        sort: 0,
        value_type: 'cumulative',
      },
      transparent: false,
      type: 'graph',
      xaxis: {
        buckets: null,
        mode: 'time',
        name: null,
        show: true,
        values: [],
      },
      yaxes: [
        {
          format: 'short',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
        {
          format: 'short',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
      ],
    },
    {
      cacheTimeout: null,
      colorBackground: false,
      colorValue: true,
      colors: [
        'rgba(245, 54, 54, 0.9)',
        'rgba(237, 129, 40, 0.89)',
        'rgba(50, 172, 45, 0.97)',
      ],
      datasource: 'prometheus',
      decimals: null,
      editable: true,
      error: false,
      format: 'none',
      gauge: {
        maxValue: 100,
        minValue: 0,
        show: false,
        thresholdLabels: false,
        thresholdMarkers: true,
      },
      gridPos: {
        h: 7,
        w: 4,
        x: 0,
        y: 27,
      },
      id: 9,
      interval: null,
      links: [],
      mappingType: 1,
      mappingTypes: [
        {
          name: 'value to text',
          value: 1,
        },
        {
          name: 'range to text',
          value: 2,
        },
      ],
      maxDataPoints: 100,
      nullPointMode: 'connected',
      nullText: null,
      postfix: ' partitions',
      postfixFontSize: '50%',
      prefix: '',
      prefixFontSize: '50%',
      rangeMaps: [
        {
          from: 'null',
          text: 'N/A',
          to: 'null',
        },
      ],
      sparkline: {
        fillColor: 'rgba(31, 118, 189, 0.18)',
        full: false,
        lineColor: 'rgb(31, 120, 193)',
        show: false,
      },
      tableColumn: '',
      targets: [
        {
          expr: 'sum(kafka_server_replicamanager_value{name="PartitionCount"})',
          format: 'time_series',
          intervalFactor: 2,
          legendFormat: '',
          refId: 'A',
          step: 20,
        },
      ],
      thresholds: '',
      title: 'Total Partition Count',
      transparent: false,
      type: 'singlestat',
      valueFontSize: '200%',
      valueMaps: [
        {
          op: '=',
          text: 'N/A',
          value: 'null',
        },
      ],
      valueName: 'current',
    },
    {
      cacheTimeout: null,
      colorBackground: false,
      colorValue: true,
      colors: [
        'rgba(65, 248, 2, 0.9)',
        'rgba(237, 129, 40, 0.89)',
        'rgba(50, 172, 45, 0.97)',
      ],
      datasource: 'prometheus',
      decimals: null,
      editable: true,
      error: false,
      format: 'none',
      gauge: {
        maxValue: 100,
        minValue: 0,
        show: false,
        thresholdLabels: false,
        thresholdMarkers: true,
      },
      gridPos: {
        h: 7,
        w: 4,
        x: 4,
        y: 27,
      },
      id: 10,
      interval: null,
      links: [],
      mappingType: 1,
      mappingTypes: [
        {
          name: 'value to text',
          value: 1,
        },
        {
          name: 'range to text',
          value: 2,
        },
      ],
      maxDataPoints: 100,
      nullPointMode: 'connected',
      nullText: null,
      postfix: ' under replicated',
      postfixFontSize: '50%',
      prefix: '',
      prefixFontSize: '50%',
      rangeMaps: [
        {
          from: 'null',
          text: 'N/A',
          to: 'null',
        },
      ],
      sparkline: {
        fillColor: 'rgba(31, 118, 189, 0.18)',
        full: false,
        lineColor: 'rgb(31, 120, 193)',
        show: false,
      },
      tableColumn: '',
      targets: [
        {
          expr: 'sum(kafka_server_replicamanager_value{name="UnderReplicatedPartitions"})',
          intervalFactor: 2,
          legendFormat: '',
          refId: 'A',
          step: 20,
        },
      ],
      thresholds: '',
      title: 'Total Under Replicated Partition Count',
      transparent: false,
      type: 'singlestat',
      valueFontSize: '200%',
      valueMaps: [
        {
          op: '=',
          text: 'N/A',
          value: 'null',
        },
      ],
      valueName: 'current',
    },
    {
      columns: [
        {
          text: 'Current',
          value: 'current',
        },
      ],
      datasource: 'prometheus',
      editable: true,
      error: false,
      fontSize: '100%',
      gridPos: {
        h: 7,
        w: 4,
        x: 8,
        y: 27,
      },
      id: 14,
      links: [],
      pageSize: null,
      scroll: true,
      showHeader: true,
      sort: {
        col: 1,
        desc: true,
      },
      styles: [
        {
          dateFormat: 'YYYY-MM-DD HH:mm:ss',
          pattern: 'Time',
          type: 'date',
        },
        {
          colorMode: 'cell',
          colors: [
            'rgba(29, 145, 24, 0.97)',
            'rgba(255, 115, 0, 0.89)',
            'rgba(245, 54, 54, 0.9)',
          ],
          decimals: 2,
          pattern: '/.*/',
          thresholds: [],
          type: 'number',
          unit: 'ms',
        },
      ],
      targets: [
        {
          expr: 'java_lang_runtime_uptime',
          intervalFactor: 2,
          legendFormat: 'Broker {{ instance }}',
          refId: 'A',
          step: 4,
        },
      ],
      title: 'Kafka Broker Uptime',
      transform: 'timeseries_aggregations',
      type: 'table',
    },
    {
      aliasColors: {},
      bars: false,
      dashLength: 10,
      dashes: false,
      datasource: 'prometheus',
      editable: true,
      error: false,
      fill: 1,
      grid: {},
      gridPos: {
        h: 7,
        w: 12,
        x: 12,
        y: 27,
      },
      id: 12,
      legend: {
        avg: false,
        current: false,
        max: false,
        min: false,
        show: true,
        total: false,
        values: false,
      },
      lines: true,
      linewidth: 2,
      links: [],
      nullPointMode: 'connected',
      percentage: false,
      pointradius: 5,
      points: false,
      renderer: 'flot',
      seriesOverrides: [],
      spaceLength: 10,
      stack: false,
      steppedLine: false,
      targets: [
        {
          expr: 'kafka_server_replicafetchermanager_value',
          intervalFactor: 2,
          metric: 'kafka_server_replicafetchermanager_value',
          refId: 'A',
          step: 2,
        },
      ],
      thresholds: [],
      timeFrom: null,
      timeShift: null,
      title: 'Max lag in messages btw follower and leader replicas',
      tooltip: {
        msResolution: false,
        shared: true,
        sort: 0,
        value_type: 'cumulative',
      },
      type: 'graph',
      xaxis: {
        buckets: null,
        mode: 'time',
        name: null,
        show: true,
        values: [],
      },
      yaxes: [
        {
          format: 'short',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
        {
          format: 'short',
          label: null,
          logBase: 1,
          max: null,
          min: null,
          show: true,
        },
      ],
    },
    {
      cacheTimeout: null,
      colorBackground: false,
      colorValue: true,
      colors: [
        'rgba(245, 54, 54, 0.9)',
        'rgba(237, 129, 40, 0.89)',
        'rgba(50, 172, 45, 0.97)',
      ],
      datasource: 'prometheus',
      decimals: null,
      editable: true,
      error: false,
      format: 'ms',
      gauge: {
        maxValue: 100,
        minValue: 0,
        show: false,
        thresholdLabels: false,
        thresholdMarkers: true,
      },
      gridPos: {
        h: 7,
        w: 20,
        x: 0,
        y: 34,
      },
      id: 5,
      interval: null,
      links: [],
      mappingType: 1,
      mappingTypes: [
        {
          name: 'value to text',
          value: 1,
        },
        {
          name: 'range to text',
          value: 2,
        },
      ],
      maxDataPoints: 100,
      nullPointMode: 'connected',
      nullText: null,
      postfix: '',
      postfixFontSize: '50%',
      prefix: '',
      prefixFontSize: '50%',
      rangeMaps: [
        {
          from: 'null',
          text: 'N/A',
          to: 'null',
        },
      ],
      sparkline: {
        fillColor: 'rgba(31, 118, 189, 0.18)',
        full: false,
        lineColor: 'rgb(31, 120, 193)',
        show: false,
      },
      tableColumn: '',
      targets: [
        {
          expr: 'java_lang_runtime_uptime',
          format: 'time_series',
          intervalFactor: 2,
          legendFormat: '',
          refId: 'A',
          step: 20,
        },
      ],
      thresholds: '',
      title: 'Kafka Broker Uptime',
      transparent: false,
      type: 'singlestat',
      valueFontSize: '80%',
      valueMaps: [
        {
          op: '=',
          text: 'N/A',
          value: 'null',
        },
      ],
      valueName: 'current',
    },
  ],
  style: 'dark',
  templating: {
    list: [],
  },
  time: {
    from: 'now-24h',
    to: 'now',
  },
  timepicker: {
    refresh_intervals: [
      '5s',
      '10s',
      '30s',
      '1m',
      '5m',
      '15m',
      '30m',
      '1h',
      '2h',
      '1d',
    ],
    time_options: ['5m', '15m', '1h', '6h', '12h', '24h', '2d', '7d', '30d'],
  },
};
