---
version: '3'

services:
  webapp:
    image: 090574062077.dkr.ecr.us-east-1.amazonaws.com/kafka-nimbus-prod
    ports:
      - 8000:8000
    volumes:
      - shared-volume:/usr/app/config
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /etc/prometheus:/prometheus
      - prometheus-data:/prometheus
      - shared-volume:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false


volumes:
  shared-volume:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local